;<?php die('');?>
isWindows=
enableAllModules=
disableInstallers=
chmodDir=509
chmodFile=436
forceHTTPSPort=
forceHTTPPort=
domainName=localhost
timeZone="Europe/Paris"
httpVersion=
theme=default
charset=UTF-8
fallbackLocale=en_US
locale=en_US
[availableLocales]
0=en_US
[modules]
jelix.enabled=on
jelix.path="lib:jelix/core-modules/jelix"
jacldb.enabled=
jacl2db.enabled=
jauth.enabled=
jauthdb.enabled=
jelix.installparam[]=copy
app.enabled=on
core.enabled=on
jelix.dbprofile=default
jacldb.dbprofile=default
jacl2.enabled=
jacl2.dbprofile=default
jacl2db.dbprofile=default
jacl.enabled=
jacl.dbprofile=default
jpref.enabled=
jpref.dbprofile=default
jauth.dbprofile=default
jauthdb.dbprofile=default
master_admin.enabled=
master_admin.dbprofile=default
jauthdb_admin.enabled=
jauthdb_admin.dbprofile=default
jacl2db_admin.enabled=
jacl2db_admin.dbprofile=default
jpref_admin.enabled=
jpref_admin.dbprofile=default
core.dbprofile=default
[coordplugins]
[tplplugins]
defaultJformsBuilder=html
defaultJformsErrorDecorator=
[responses]
html=myHtmlResponse
htmlerror=jResponseHtmlError
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/var/www/html/app/app/responses/myHtmlResponse.class.php"
htmlerror.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtmlError.class.php"
basichtml.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseXmlrpc.class.php"
xml.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseZip.class.php"
css.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseCss.class.php"
htmlfragment.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtml.class.php"
[_coreResponses]
html=jResponseHtml
htmlerror=jResponseHtmlError
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtml.class.php"
htmlerror.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtmlError.class.php"
basichtml.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseXmlrpc.class.php"
xml.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseZip.class.php"
css.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseCss.class.php"
htmlfragment.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/var/www/html/vendor/jelix/jelix/lib/jelix/core/response/jResponseHtml.class.php"
[jResponseHtml]
plugins=
minifyCSS=
minifyJS=on
minifyExcludeCSS=
minifyExcludeJS="jelix/ckeditor5/ckeditor.js"
minifyEntryPoint=minify.php
[debugbar]
plugins="sqllog,sessiondata,defaultlog"
defaultPosition=right
errors_openon=error
[error_handling]
messageLogFormat="%date%\t%ip%\t%typeerror%\t[%code%]\t%msg%\n\tat: %file%\t%line%\n\turl: %url%\n\t%http_method%: %params%\n\treferer: %referer%\n%trace%\n\n"
errorMessage="A technical error has occured (code: %code%). Sorry for this inconvenience."
sensitiveParameters[]=password
sensitiveParameters[]=passwd
sensitiveParameters[]=pwd
[compilation]
sourceFileResolutionInCache=
checkCacheFiletime=on
force=
[urlengine]
enableParser=on
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/"
backendBasePath=
forceProxyProtocol=
checkHttpsOnParsing=on
jelixWWWPath="/jelix/"
jqueryPath="/jelix/jquery/"
notFoundAct="jelix~error:notfound"
significantFile=urls.xml
localSignificantFile=localurls.xml
urlScript="/index.php"
urlScriptPath="/"
urlScriptName=index.php
urlScriptId=index
urlScriptIdenc=index
documentRoot="/var/www/html"
assetsRevision=
assetsRevisionParameter=_r
assetsRevQueryUrl=
[logger]
_all=
default=file
error=file
warning=file
notice=file
deprecated=
strict=
debug=
sql=
soap=
[fileLogger]
default=messages.log
error=errors.log
warning=errors.log
notice=errors.log
deprecated=errors.log
strict=errors.log
debug=debug.log
[memorylogger]
default=20
error=10
warning=10
notice=10
deprecated=10
strict=10
debug=20
sql=20
soap=20
[mailLogger]
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
[syslogLogger]
facility=184
ident="php-%sapi%-%domain%[%pid%]"
[stderrLogger]
[stdoutLogger]
[mailer]
webmasterEmail="root@localhost"
webmasterName=
mailerType=file
hostname=
sendmailPath="/usr/sbin/sendmail"
filesDir="mails/"
smtpProfile=mailer
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
copyToFiles=
debugModeEnabled=
debugReceiversType=1
debugReceivers=
debugReceiversWhiteList=
debugFrom=
debugFromName=
debugSubjectPrefix=
debugBodyIntroduction=
debugSmtpLevel=0
[acl]
driver=
[acl2]
driver=
authAdapterClass=jAcl2JAuthAdapter
[sessions]
start=1
shared_session=
cookieSecure=
cookieHttpOnly=on
cookieLifetime=0
cookieSameSite=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.time.input=menulists
controls.datetime.months.labels=names
datepicker=default
datetimepicker=default
timepicker=
captcha=simple
captcha.simple.validator="\jelix\forms\Captcha\SimpleCaptchaValidator"
captcha.simple.widgettype=captcha
captcha.recaptcha.validator="\jelix\forms\Captcha\ReCaptchaValidator"
captcha.recaptcha.widgettype=recaptcha
flagPrepareObjectFromControlsContactArrayValues=0
[jforms_builder_html]
[htmleditors]
default.engine.name=ckeditor
ckdefault.engine.name=ckeditor
ckfull.engine.name=ckeditor
ckbasic.engine.name=ckeditor
[wikieditors]
default.engine.name=wr3
default.wiki.rules=wr3_to_xhtml
[webassets]
useCollection=common
[webassets_common]
jquery.js="$jelix/jquery/jquery.min.js"
jquery_ui.js="$jelix/jquery/ui/jquery-ui.min.js"
jquery_ui.css[]="$jelix/jquery/ui/jquery-ui.min.css"
jquery_ui.require=jquery
jforms_html.js[]="$jelix/js/jforms_jquery.js"
jforms_html.css="$jelix/design/jform.css"
jforms_html.require=jquery
jforms_html_light.js="$jelix/js/jforms_light.js"
jforms_html_light.css="$jelix/design/jform.css"
jforms_datepicker_default.css=
jforms_datepicker_default.js[]="$jelix/jquery/ui/i18n/datepicker-$lang.js"
jforms_datepicker_default.js[]="$jelix/js/jforms/datepickers/default/ui.$lang.js"
jforms_datepicker_default.js[]="$jelix/js/jforms/datepickers/default/init.js"
jforms_datepicker_default.require=jquery_ui
jforms_datetimepicker_default.require=jforms_datepicker_default
jforms_datetimepicker_default.js[]="$jelix/js/jforms/datetimepickers/default/init.js"
jforms_datetimepicker_default.js[]="$jelix/jquery/jquery-ui-timepicker-addon.js"
jforms_datetimepicker_default.css="$jelix/jquery/jquery-ui-timepicker-addon.css"
jforms_htmleditor_default.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_default.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_default.js[]="$jelix/js/jforms/htmleditors/ckeditor_default.js"
jforms_htmleditor_ckdefault.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckdefault.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckdefault.js[]="$jelix/js/jforms/htmleditors/ckeditor_ckdefault.js"
jforms_htmleditor_ckfull.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckfull.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckfull.js[]="$jelix/js/jforms/htmleditors/ckeditor_ckfull.js"
jforms_htmleditor_ckbasic.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckbasic.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckbasic.js[]="$jelix/js/jforms/htmleditors/ckeditor_ckbasic.js"
jforms_wikieditor_default.js[]="$jelix/markitup/jquery.markitup.js"
jforms_wikieditor_default.js[]="$jelix/markitup/sets/wr3/$locale.js"
jforms_wikieditor_default.css[]="$jelix/markitup/skins/simple/style.css"
jforms_wikieditor_default.css[]="$jelix/markitup/sets/wr3/style.css"
jforms_wikieditor_default.require=jquery
jforms_imageupload.js[]="$jelix/js/cropper.min.js"
jforms_imageupload.js[]="$jelix/js/jforms/choice.js"
jforms_imageupload.js[]="$jelix/js/jforms/imageSelector.js"
jforms_imageupload.css[]="$jelix/js/cropper.min.css"
jforms_imageupload.require=jquery_ui
jforms_autocomplete.js[]="$jelix/js/jforms/jAutocomplete.jqueryui.js"
jforms_autocomplete.require=jquery_ui
jforms_autocompleteajax.js[]="$jelix/js/jforms/jAutocompleteAjax.jqueryui.js"
jforms_autocompleteajax.require=jquery_ui
swjs.js="$jelix/jquery/flash/jquery.flash.js"
swjs.require=jquery
[zones]
disableCache=
[classbindings]
[imagemodifier]
src_url=
src_path=
cache_url=
cache_path=
[rootUrls]
jelix.cache="cache/"
[langToLocale]
locale[]=en_US
[disabledListeners]
[mimeTypes]
[coordplugin_auth]
persistant_encryption_key=
[recaptcha]
sitekey=
secret=
theme=
type=
size=
tabindex=
[session]
storage=
[_allBasePath]
0="/var/www/html/vendor/jelix/jelix/lib/jelix-modules"
1="/var/www/html/vendor/jelix/jelix/lib/jelix-admin-modules"
2="/var/www/html/app/modules"
3="/var/www/html/vendor/jelix/jelix/lib/jelix-plugins/cache/"
4="/var/www/html/vendor/jelix/jelix/lib/jelix-plugins/kvdb/"
5="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacldb/plugins/acl/"
6="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2/plugins/coord/"
7="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2/plugins/tpl/"
8="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2db/plugins/acl2/"
9="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl/plugins/coord/"
10="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl/plugins/tpl/"
[_modulesPathList]
jelix="/var/www/html/vendor/jelix/jelix/lib/jelix/core-modules/jelix/"
core="/var/www/html/app/modules/core/"
[_pluginsPathList_htmlresponse]
debugbar="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/htmlresponse/debugbar/"
[_pluginsPathList_profiles]
jdb="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/profiles/jdb/"
[_pluginsPathList_cache]
redis_ext="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/cache/redis_ext/"
db="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/cache/db/"
memcache="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/cache/memcache/"
file="/var/www/html/vendor/jelix/jelix/lib/jelix-plugins/cache/file/"
[_pluginsPathList_coord]
traceexec="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/coord/traceexec/"
autolocale="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/coord/autolocale/"
history="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/coord/history/"
auth="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/coord/auth/"
jacl2="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2/plugins/coord/jacl2/"
jacl="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl/plugins/coord/jacl/"
[_tplpluginsPathList_html]
0="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/tpl/html/"
[_tplpluginsPathList_common]
0="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl/plugins/tpl/common/"
1="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2/plugins/tpl/common/"
2="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/tpl/common/"
[_tplpluginsPathList_xml]
0="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/tpl/xml/"
[_tplpluginsPathList_ltx2pdf]
0="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/tpl/text/"
[_pluginsPathList_db]
pgsql="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/"
mssql="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/db/mssql/"
oci="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/db/oci/"
sqlite3="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/db/sqlite3/"
sqlsrv="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/db/sqlsrv/"
mysqli="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/db/mysqli/"
[_pluginsPathList_auth]
ldap="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/auth/ldap/"
db="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/auth/db/"
class="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/auth/class/"
[_pluginsPathList_kvdb]
redis_ext="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/kvdb/redis_ext/"
dba="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/kvdb/dba/"
db="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/kvdb/db/"
file2="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/kvdb/file2/"
memcache="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/kvdb/memcache/"
file="/var/www/html/vendor/jelix/jelix/lib/jelix-plugins/kvdb/file/"
[_pluginsPathList_debugbar]
sqllog="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/debugbar/sqllog/"
defaultlog="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/debugbar/defaultlog/"
sessiondata="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/debugbar/sessiondata/"
soaplog="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/debugbar/soaplog/"
[_pluginsPathList_jforms]
html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/jforms/html/"
htmllight="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/jforms/htmllight/"
[_pluginsPathList_configcompiler]
responses="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/responses/"
nsautoloader="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/nsautoloader/"
locales="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/locales/"
session="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/session/"
webassets="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/webassets/"
debugbar="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/debugbar/"
assetsrevision="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/configcompiler/assetsrevision/"
[_pluginsPathList_logger]
legacysyslog="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/logger/legacysyslog/"
firebug="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/logger/firebug/"
soapfile="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/logger/soapfile/"
[_pluginsPathList_formbuilder]
html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formbuilder/html/"
[_pluginsPathList_daobuilder]
pgsql="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/daobuilder/pgsql/"
mssql="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/daobuilder/mssql/"
oci="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/daobuilder/oci/"
mysql="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/daobuilder/mysql/"
sqlite="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/daobuilder/sqlite/"
sqlsrv="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/daobuilder/sqlsrv/"
[_pluginsPathList_formwidget]
html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/html/"
upload2_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/upload2_html/"
recaptcha_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/recaptcha_html/"
textarea_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/textarea_html/"
htmleditor_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/htmleditor_html/"
date_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/date_html/"
secret_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/secret_html/"
reset_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/reset_html/"
checkbox_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/checkbox_html/"
listbox_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/listbox_html/"
radiobuttons_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/radiobuttons_html/"
output_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/output_html/"
datetime_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/datetime_html/"
input_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/input_html/"
group_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/group_html/"
time_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/time_html/"
checkboxes_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/checkboxes_html/"
autocompleteajax_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/autocompleteajax_html/"
color_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/color_html/"
menulist_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/menulist_html/"
wikieditor_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/wikieditor_html/"
submit_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/submit_html/"
imageupload_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/imageupload_html/"
captcha_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/captcha_html/"
autocomplete_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/autocomplete_html/"
choice_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/choice_html/"
upload_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/upload_html/"
button_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/button_html/"
secretconfirm_html="/var/www/html/vendor/jelix/jelix/lib/jelix/plugins/formwidget/secretconfirm_html/"
[_pluginsPathList_acl]
db="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacldb/plugins/acl/db/"
[_pluginsPathList_acl2]
db="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2db/plugins/acl2/db/"
dbcache="/var/www/html/vendor/jelix/jelix/lib/jelix-modules/jacl2db/plugins/acl2/dbcache/"
[_autoload_class]
[_autoload_namespace]
[_autoload_classpattern]
[_autoload_includepathmap]
[_autoload_includepath]
[_autoload_namespacepathmap]
Jelix\JelixModule="/var/www/html/vendor/jelix/jelix/lib/jelix/core-modules/jelix/./|.php"
[_autoload_autoloader]
[compiled_webassets_common]
dependencies_order[]=jquery
dependencies_order[]=jquery_ui
dependencies_order[]=jforms_html
dependencies_order[]=jforms_html_light
dependencies_order[]=jforms_datepicker_default
dependencies_order[]=jforms_datetimepicker_default
dependencies_order[]=jforms_htmleditor_default
dependencies_order[]=jforms_htmleditor_ckdefault
dependencies_order[]=jforms_htmleditor_ckfull
dependencies_order[]=jforms_htmleditor_ckbasic
dependencies_order[]=jforms_wikieditor_default
dependencies_order[]=jforms_imageupload
dependencies_order[]=jforms_autocomplete
dependencies_order[]=jforms_autocompleteajax
dependencies_order[]=swjs
webassets_jquery.js[]="u>/jelix/jquery/jquery.min.js>"
webassets_jquery_ui.deps[]=jquery
webassets_jquery_ui.js[]="u>/jelix/jquery/ui/jquery-ui.min.js>"
webassets_jquery_ui.css[]="u>/jelix/jquery/ui/jquery-ui.min.css>"
webassets_jforms_html.deps[]=jquery
webassets_jforms_html.js[]="u>/jelix/js/jforms_jquery.js>"
webassets_jforms_html.css[]="u>/jelix/design/jform.css>"
webassets_jforms_html_light.js[]="u>/jelix/js/jforms_light.js>"
webassets_jforms_html_light.css[]="u>/jelix/design/jform.css>"
webassets_jforms_datepicker_default.deps[]=jquery_ui
webassets_jforms_datepicker_default.deps[]=jquery
webassets_jforms_datepicker_default.js[]="l>/jelix/jquery/ui/i18n/datepicker-$lang.js>"
webassets_jforms_datepicker_default.js[]="l>/jelix/js/jforms/datepickers/default/ui.$lang.js>"
webassets_jforms_datepicker_default.js[]="u>/jelix/js/jforms/datepickers/default/init.js>"
webassets_jforms_datetimepicker_default.deps[]=jforms_datepicker_default
webassets_jforms_datetimepicker_default.deps[]=jquery_ui
webassets_jforms_datetimepicker_default.deps[]=jquery
webassets_jforms_datetimepicker_default.js[]="u>/jelix/js/jforms/datetimepickers/default/init.js>"
webassets_jforms_datetimepicker_default.js[]="u>/jelix/jquery/jquery-ui-timepicker-addon.js>"
webassets_jforms_datetimepicker_default.css[]="u>/jelix/jquery/jquery-ui-timepicker-addon.css>"
webassets_jforms_htmleditor_default.js[]="u>/jelix/ckeditor5/ckeditor.js>"
webassets_jforms_htmleditor_default.js[]="l>/jelix/ckeditor5/translations/$lang.js>"
webassets_jforms_htmleditor_default.js[]="u>/jelix/js/jforms/htmleditors/ckeditor_default.js>"
webassets_jforms_htmleditor_ckdefault.js[]="u>/jelix/ckeditor5/ckeditor.js>"
webassets_jforms_htmleditor_ckdefault.js[]="l>/jelix/ckeditor5/translations/$lang.js>"
webassets_jforms_htmleditor_ckdefault.js[]="u>/jelix/js/jforms/htmleditors/ckeditor_ckdefault.js>"
webassets_jforms_htmleditor_ckfull.js[]="u>/jelix/ckeditor5/ckeditor.js>"
webassets_jforms_htmleditor_ckfull.js[]="l>/jelix/ckeditor5/translations/$lang.js>"
webassets_jforms_htmleditor_ckfull.js[]="u>/jelix/js/jforms/htmleditors/ckeditor_ckfull.js>"
webassets_jforms_htmleditor_ckbasic.js[]="u>/jelix/ckeditor5/ckeditor.js>"
webassets_jforms_htmleditor_ckbasic.js[]="l>/jelix/ckeditor5/translations/$lang.js>"
webassets_jforms_htmleditor_ckbasic.js[]="u>/jelix/js/jforms/htmleditors/ckeditor_ckbasic.js>"
webassets_jforms_wikieditor_default.deps[]=jquery
webassets_jforms_wikieditor_default.js[]="u>/jelix/markitup/jquery.markitup.js>"
webassets_jforms_wikieditor_default.js[]="l>/jelix/markitup/sets/wr3/$locale.js>"
webassets_jforms_wikieditor_default.css[]="u>/jelix/markitup/skins/simple/style.css>"
webassets_jforms_wikieditor_default.css[]="u>/jelix/markitup/sets/wr3/style.css>"
webassets_jforms_imageupload.deps[]=jquery_ui
webassets_jforms_imageupload.deps[]=jquery
webassets_jforms_imageupload.js[]="u>/jelix/js/cropper.min.js>"
webassets_jforms_imageupload.js[]="u>/jelix/js/jforms/choice.js>"
webassets_jforms_imageupload.js[]="u>/jelix/js/jforms/imageSelector.js>"
webassets_jforms_imageupload.css[]="u>/jelix/js/cropper.min.css>"
webassets_jforms_autocomplete.deps[]=jquery_ui
webassets_jforms_autocomplete.deps[]=jquery
webassets_jforms_autocomplete.js[]="u>/jelix/js/jforms/jAutocomplete.jqueryui.js>"
webassets_jforms_autocompleteajax.deps[]=jquery_ui
webassets_jforms_autocompleteajax.deps[]=jquery
webassets_jforms_autocompleteajax.js[]="u>/jelix/js/jforms/jAutocompleteAjax.jqueryui.js>"
webassets_swjs.deps[]=jquery
webassets_swjs.js[]="u>/jelix/jquery/flash/jquery.flash.js>"
